

module.exports.registerService = function (app, trackHistory, trackPicture) {
    console.log('register Countryservice');

    countries = {
        AL: 'Albania (Republic of)',
        AD: 'Andorra (Principality of)',
        AT: 'Austria',
        BE: 'Belgium',
        BG: 'Bulgaria (Republic of)',
        VA: 'Vatican City State',
        CY: 'Cyprus (Republic of)',
        DE: 'Germany (Federal Republic of)',
        GE: 'Georgia',
        MD: 'Moldova (Republic of)',
        MT: 'Malta',
        AM: 'Armenia (Republic of)',
        DK: 'Denmark',
        ES: 'Spain',
        FR: 'France',
        FI: 'Finland',
        FO: 'Faroe Islands - Denmark',
        GB: 'United Kingdom of Great Britain and Northern Ireland',
        GI: 'Gibraltar - United Kingdom of Great Britain and Northern Ireland',
        GR: 'Greece',
        MA: 'Morocco (Kingdom of)',
        HU: 'Hungary',
        NL: 'Netherlands (Kingdom of the)',
        IT: 'Italy',
        IE: 'Ireland',
        IS: 'Iceland',
        LI: 'Liechtenstein (Principality of)',
        LU: 'Luxembourg',
        MC: 'Monaco (Principality of)',
        NO: 'Norway',
        PO: 'Poland (Republic of)',
        ME: 'Montenegro',
        PT: 'Portugal',
        RO: 'Romania',
        SE: 'Sweden',
        SK: 'Slovak Republic',
        SM: 'San Marino (Republic of)',
        CH: 'Switzerland (Confederation of)',
        CZ: 'Czech Republic',
        TR: 'Turkey',
        UA: 'Ukraine',
        RU: 'Russian Federation',
        MK: 'The Former Yugoslav Republic of Macedonia',
        LV: 'Latvia (Republic of)',
        EE: 'Estonia (Republic of)',
        LT: 'Lithuania (Republic of)',
        SI: 'Slovenia (Republic of)',
        RS: 'Serbia (Republic of)',
        AI: 'Anguilla - United Kingdom of Great Britain and Northern Ireland',
        US: 'United States of America',
        AG: 'Antigua and Barbuda',
        SX: 'Sint Maarten, Bonaire, Curaçao (Dutch part) - Netherlands (Kingdom of the)',
        AW: 'Aruba - Netherlands (Kingdom of the)',
        BS: 'Bahamas (Commonwealth of the)',
        BM: 'Bermuda - United Kingdom of Great Britain and Northern Ireland',
        BZ: 'Belize',
        BB: 'Barbados',
        CA: 'Canada',
        KY: 'Cayman Islands - United Kingdom of Great Britain and Northern Ireland',
        CR: 'Costa Rica',
        CU: 'Cuba',
        DM: 'Dominica (Commonwealth of)',
        DO: 'Dominican Republic',
        GP: 'Guadeloupe (French Department of) - France',
        GD: 'Grenada',
        GL: 'Greenland - Denmark',
        GT: 'Guatemala (Republic of)',
        HN: 'Honduras (Republic of)',
        HT: 'Haiti (Republic of)',
        JM: 'Jamaica',
        KN: 'Saint Kitts and Nevis (Federation of)',
        LC: 'Saint Lucia',
        MX: 'Mexico',
        MQ: 'Martinique (French Department of) - France',
        MS: 'Montserrat - United Kingdom of Great Britain and Northern Ireland',
        NI: 'Nicaragua',
        PA: 'Panama (Republic of)',
        PR: 'Puerto Rico - United States of America',
        SV: 'El Salvador (Republic of)',
        PM: 'Saint Pierre and Miquelon (Territorial Collectivity of) - France',
        TT: 'Trinidad and Tobago',
        TC: 'Turks and Caicos Islands - United Kingdom of Great Britain and Northern Ireland',
        VC: 'Saint Vincent and the Grenadines',
        VG: 'British Virgin Islands - United Kingdom of Great Britain and Northern Ireland',
        VI: 'United States Virgin Islands - United States of America',
        AF: 'Afghanistan',
        SA: 'Saudi Arabia (Kingdom of)',
        BD: 'Bangladesh (People\'s Republic of)',
        BH: 'Bahrain (Kingdom of)',
        BT: 'Bhutan (Kingdom of)',
        CN: 'China (People\'s Republic of)',
        TW: 'Taiwan (Province of China) - China (People\'s Republic of)',
        LK: 'Sri Lanka (Democratic Socialist Republic of)',
        IN: 'India (Republic of)',
        IR: 'Iran (Islamic Republic of)',
        AZ: 'Azerbaijan (Republic of)',
        IQ: 'Iraq (Republic of)',
        IL: 'Israel (State of)',
        JP: 'Japan',
        TM: 'Turkmenistan',
        KZ: 'Kazakhstan (Republic of)',
        UZ: 'Uzbekistan (Republic of)',
        JO: 'Jordan (Hashemite Kingdom of)',
        KR: 'Korea (Republic of)',
        PS: 'State of Palestine (In accordance with Resolution 99 Rev. Guadalajara, 2010)',
        KP: 'Democratic People\'s Republic of Korea',
        KW: 'Kuwait (State of)',
        LB: 'Lebanon',
        KG: 'Kyrgyz Republic',
        MO: 'Macao (Special Administrative Region of China) - China (People\'s Republic of)',
        MV: 'Maldives (Republic of)',
        MN: 'Mongolia',
        NP: 'Nepal (Federal Democratic Republic of)',
        OM: 'Oman (Sultanate of)',
        PK: 'Pakistan (Islamic Republic of)',
        QA: 'Qatar (State of)',
        SY: 'Syrian Arab Republic',
        AE: 'United Arab Emirates',
        TJ: 'Tajikistan (Republic of)',
        YE: 'Yemen (Republic of)',
        HK: 'Hong Kong (Special Administrative Region of China) - China (People\'s Republic of)',
        BA: 'Bosnia and Herzegovina',
        AU: 'Australia',
        MM: 'Myanmar (Union of)',
        BN: 'Brunei Darussalam',
        FM: 'Micronesia (Federated States of)',
        PW: 'Palau (Republic of)',
        NZ: 'New Zealand',
        KH: 'Cambodia (Kingdom of)',
        CX: 'Christmas Island (Indian Ocean) - Australia',
        CK: 'Cook Islands - New Zealand',
        FJ: 'Fiji (Republic of)',
        CC: 'Cocos (Keeling) Islands - Australia',
        ID: 'Indonesia (Republic of)',
        KI: 'Kiribati (Republic of)',
        LA: 'Lao People\'s Democratic Republic',
        MY: 'Malaysia',
        MP: 'Northern Mariana Islands (Commonwealth of the) - United States of America',
        MH: 'Marshall Islands (Republic of the)',
        NC: 'New Caledonia - France',
        NU: 'Niue - New Zealand',
        NR: 'Nauru (Republic of)',
        PF: 'French Polynesia - France',
        PH: 'Philippines (Republic of the)',
        PG: 'Papua New Guinea',
        PN: 'Pitcairn Island - United Kingdom of Great Britain and Northern Ireland',
        SB: 'Solomon Islands',
        AS: 'American Samoa - United States of America',
        WS: 'Samoa (Independent State of)',
        SG: 'Singapore (Republic of)',
        TH: 'Thailand',
        TO: 'Tonga (Kingdom of)',
        TV: 'Tuvalu',
        VN: 'Viet Nam (Socialist Republic of)',
        VU: 'Vanuatu (Republic of)',
        WF: 'Wallis and Futuna Islands - France',
        ZA: 'South Africa (Republic of)',
        AO: 'Angola (Republic of)',
        DZ: 'Algeria (People\'s Democratic Republic of)',
        SH: 'Saint Helena - United Kingdom of Great Britain and Northern Ireland',
        BI: 'Burundi (Republic of)',
        BJ: 'Benin (Republic of)',
        BW: 'Botswana (Republic of)',
        CF: 'Central African Republic',
        CM: 'Cameroon (Republic of)',
        CG: 'Democratic Republic of the Congo',
        KM: 'Comoros (Union of the)',
        CV: 'Cabo Verde (Republic of)',
        CI: 'Côte d\'Ivoire (Republic of)',
        DJ: 'Djibouti (Republic of)',
        EG: 'Egypt (Arab Republic of)',
        ET: 'Ethiopia (Federal Democratic Republic of)',
        ER: 'Eritrea',
        GA: 'Gabonese Republic',
        GH: 'Ghana',
        GM: 'Gambia (Republic of the)',
        GW: 'Guinea-Bissau (Republic of)',
        GQ: 'Equatorial Guinea (Republic of)',
        GN: 'Guinea (Republic of)',
        BF: 'Burkina Faso',
        KE: 'Kenya (Republic of)',
        LR: 'Liberia (Republic of)',
        SD: 'Sudan (Republic of the)',
        LY: 'Libya',
        LS: 'Lesotho (Kingdom of)',
        MU: 'Mauritius (Republic of)',
        MG: 'Madagascar (Republic of)',
        ML: 'Mali (Republic of)',
        MZ: 'Mozambique (Republic of)',
        MR: 'Mauritania (Islamic Republic of)',
        MW: 'Malawi',
        NE: 'Niger (Republic of the)',
        NG: 'Nigeria (Federal Republic of)',
        NA: 'Namibia (Republic of)',
        RE: 'Reunion (French Department of) - France',
        RW: 'Rwanda (Republic of)',
        SN: 'Senegal (Republic of)',
        SC: 'Seychelles (Republic of)',
        SO: 'Somalia (Federal Republic of)',
        SL: 'Sierra Leone',
        ST: 'Sao Tome and Principe (Democratic Republic of)',
        SZ: 'Swaziland (Kingdom of)',
        TD: 'Chad (Republic of)',
        TG: 'Togolese Republic',
        TN: 'Tunisia',
        TZ: 'Tanzania (United Republic of)',
        UG: 'Uganda (Republic of)',
        ZM: 'Zambia (Republic of)',
        ZW: 'Zimbabwe (Republic of)',
        AR: 'Argentine Republic',
        BR: 'Brazil (Federative Republic of)',
        BO: 'Bolivia (Plurinational State of)',
        CL: 'Chile',
        CO: 'Colombia (Republic of)',
        EC: 'Ecuador',
        FK: 'Falkland Islands (Malvinas) - United Kingdom of Great Britain and Northern Ireland',
        GF: 'Guiana (French Department of) - France',
        GY: 'Guyana',
        PY: 'Paraguay (Republic of)',
        PE: 'Peru',
        SR: 'Suriname (Republic of)',
        UY: 'Uruguay (Eastern Republic of)',
        VE: 'Venezuela (Bolivarian Republic of)'
    };

    app.get('/country', function (req, res) {
        res.json(countries);
    });

    app.get('/country/:code', function (req, res) {
        var code = req.params.code || 'XX';
        code = code.toUpperCase();
        var countryName = countries[code];
        if (countryName === undefined)
            res.status(404).send('Country not found !');
        else {
            res.send(countryName);
        }
    });
};